### ISSUE TITLE
compile error with Postgres12

### ISSUE THREAD

**Issue by skywardfire1** [csimsek/pgsql-fio#10]
ubuntu 16.04 lts with postgresql-server-dev-12 and libghc-regex-base-dev installed.

Everything's great on PSQL11, but there's a compile error on 12. Please take into consideration.

`sudo make install
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fPIC -pie -fno-omit-frame-pointer -fPIC -I. -I./ -I/usr/include/postgresql/12/server -I/usr/include/postgresql/internal -I/usr/include/x86_64-linux-gnu -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5  -c -o fio.o fio.c

gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fPIC -pie -fno-omit-frame-pointer -fPIC -I. -I./ -I/usr/include/postgresql/12/server -I/usr/include/postgresql/internal -I/usr/include/x86_64-linux-gnu -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5  -c -o writefile.o writefile.c

In file included from /usr/include/postgresql/12/server/postgres.h:47:0,
                 from fio.h:41,
                 from writefile.c:30:
writefile.c: In function ‘fio_writefile’:
writefile.c:68:69: error: called object ‘__errno_location’ is not a function or function pointer
         elog(ERROR, "cannot open file: %s (%s)", filename, strerror(errno));
                                                                     ^
/usr/include/postgresql/12/server/utils/elog.h:221:23: note: in definition of macro ‘elog’
   elog_finish(elevel, __VA_ARGS__); \
                       ^
/usr/include/postgresql/12/server/utils/elog.h:83:41: note: declared here
 #define pg_prevent_errno_in_scope() int __errno_location pg_attribute_unused()
                                         ^
/usr/include/postgresql/12/server/utils/elog.h:219:3: note: in expansion of macro ‘pg_prevent_errno_in_scope’
   pg_prevent_errno_in_scope(); \
   ^
writefile.c:68:9: note: in expansion of macro ‘elog’
         elog(ERROR, "cannot open file: %s (%s)", filename, strerror(errno));
         ^
<встроенное>: ошибка выполнения рецепта для цели «writefile.o»
make: *** [writefile.o] Ошибка 1
`

**Comment by csimsek** [comment]
Thanks for the report. It might me fixed with last commits. Can you please check and confirm?

Regards
-Cafer
