### ISSUE TITLE
test file missing: sql/fio.sql: No such file

### ISSUE THREAD

**Issue by joelonsql** [csimsek/pgsql-fio#15]
The test specified in the Makefile "REGRESS = fio" is missing.
Maybe it exists locally on your machine and has just not been added to the git repo?

    $ make installcheck
    /usr/lib/postgresql/13/lib/pgxs/src/makefiles/../../src/test/regress/pg_regress --inputdir=./ --bindir='/usr/lib/postgresql/13/bin'    --dbname=contrib_regression fio
    (using postmaster on Unix socket, default port)
    ============== dropping database "contrib_regression" ==============
    DROP DATABASE
    ============== creating database "contrib_regression" ==============
    CREATE DATABASE
    ALTER DATABASE
    ============== running regression test queries        ==============
    test fio                          ... /bin/sh: 1: cannot open /home/joel/postgresql-extensions/pgsql-fio/sql/fio.sql: No such file
    diff: /home/joel/postgresql-extensions/pgsql-fio/expected/fio.out: No such file or directory
    diff: /home/joel/postgresql-extensions/pgsql-fio/results/fio.out: No such file or directory
    diff command failed with status 512: diff  "/home/joel/postgresql-extensions/pgsql-fio/expected/fio.out" "/home/joel/postgresql-extensions/pgsql-fio/results/fio.out" > "/home/joel/postgresql-extensions/pgsql-fio/results/fio.out.diff"
    make: *** [/usr/lib/postgresql/13/lib/pgxs/src/makefiles/pgxs.mk:420: installcheck] Error 2

**Comment by csimsek** [comment]
Hello,

You don't need to run `installcheck`. I didn't implement any tests yet.

Thanks.

**Comment by csimsek** [comment]
I have removed the line from `Makefile`. But you triggered me for adding tests. Thank you :)
