### ISSUE TITLE
fio_readfile fails with error where fio_readdir succeed

### ISSUE THREAD

**Issue by malcook** [csimsek/pgsql-fio#5]
I find that

    select fio_readfile('/a/b/c/d.yml')

fails, but

    select fio_readdir('/a/b/c/')

correctly lists the directory contents as a table.

This is in postgresql version 9.6

Any ideas for me?

Thanks!

**Comment by csimsek** [comment]
Hi @malcook,

Thanks for your feedback.

Can you give some details about the fail? Is there any error message?

Regards,

**Comment by malcook** [comment]
of course.  There is not much of a message.  Simply:

    ERROR: can not open file: /a/b/c/d.yml

**Comment by csimsek** [comment]
Do you have access to server?

If yes, can you send the result of the following command?

`file /a/b/c/d.yml`

PS: check the read permissions for the file. It should be readable by postgres user.

**Comment by malcook** [comment]
Yes, it is

    /a/b/c/d.yml: ASCII text

I ran it three times and got the same result, as the logged on user, and as the postgres user, and as root on the host.

**Comment by csimsek** [comment]
Which OS you are using for Postgres? If Linux, which distro and version?

**Comment by malcook** [comment]
Linux
Centos 7

**Comment by csimsek** [comment]
Thank you,

I will test and inspect the issue.

**Comment by malcook** [comment]
Very good.  Thanks for you help.  I’m going to sleep… long night coding…

**Comment by csimsek** [comment]
I saw the issue. Fixed in last commits. You can pull it again and drop existing extension installation before start.

Please confirm and close the issue.

Thanks,

**Comment by malcook** [comment]
Fix confirmed!  Thank you.
