### ISSUE TITLE
How to compile for PostgreSQL 10?

### ISSUE THREAD

**Issue by loveencounterflow** [csimsek/pgsql-fio#7]
Hi,

today I did

```bash
sudo apt install postgresql-server-dev-10
git clone https://github.com/csimsek/pgsql-fio/
cd pgsql-fio
sudo make install
```

which did work. But then

```sql
create extension if not exists fio;
select fio_readdir('/usr/', '*');
```

quit with 

```
psql:db/experiments/pgsql_fio.sql:3: ERROR:  incompatible library "/usr/lib/postgresql/10/lib/fio.so": version mismatch
DETAIL:  Server is version 10, library is version 9.6.
```

How can I update or configure `pgsql-fio` so that it works for PostgreSQL 10?

**Comment by csimsek** [comment]
Hello,

Make sure your `pg_config` command is pointing to correct version with that command `$(which pg_config)|grep ^VERSION`.

If it's not correct, you can edit `Makefile` for the correct version.

**Comment by loveencounterflow** [comment]
Thanks for your answer. If I understand correctly, 

```bash
which pg_config
> /usr/bin/pg_config
pg_config | grep ^VERSION
> VERSION = PostgreSQL 10.2 (Ubuntu 10.2-1.pgdg16.04+1)
```

so that tells me `pg_config` is in the correct location (on the path) and returns the correct version. Until yesterday I had both 9.6 and remnants of 9.5 on my machine, but I uninstalled everything except version 10, and added `server-dev` for Postgres 10. Indeed, `apt list --installed | grep postgres | less` would seem to agree:

```
libgda-5.0-postgres/xenial,now 5.2.4-1ubuntu1 amd64 [installed]
postgresql/now 10+188.pgdg16.04+1 all [installed,upgradable to: 10+190.pgdg16.04+1]
postgresql-10/xenial-pgdg,now 10.2-1.pgdg16.04+1 amd64 [installed]
postgresql-10-pldebugger/xenial-pgdg,now 1:1.0-3-g71ac998-1.pgdg16.04+1 amd64 [installed]
postgresql-10-pllua/xenial-pgdg,now 1:1.1.0-2.pgdg16.04+1 amd64 [installed]
postgresql-10-plsh/xenial-pgdg,now 1.20171014-1.pgdg16.04+1 amd64 [installed]
postgresql-10-unit/xenial-pgdg,now 5.0-1.pgdg16.04+1 amd64 [installed]
postgresql-client-10/now 10.1-1.pgdg16.04+1 amd64 [installed,upgradable to: 10.2-1.pgdg16.04+1]
postgresql-client-common/now 188.pgdg16.04+1 all [installed,upgradable to: 190.pgdg16.04+1]
postgresql-common/now 188.pgdg16.04+1 all [installed,upgradable to: 190.pgdg16.04+1]
postgresql-plpython3-10/xenial-pgdg,now 10.2-1.pgdg16.04+1 amd64 [installed]
postgresql-server-dev-10/xenial-pgdg,now 10.2-1.pgdg16.04+1 amd64 [installed]
```
> you can edit Makefile for the correct version

OK but where; there's no obvious place for it AFAICS:

```make
MODULE_big = fio
OBJS = fio.o writefile.o readfile.o readdir.o mkdir.o chmod.o utils.o
EXTENSION = fio
DATA = fio--1.0.sql
REGRESS = fio
EXTRA-CLEAN =

#PG_CONFIG = /usr/pgsql-9.3/bin/pg_config
PG_CONFIG = /usr/bin/pg_config

SHLIB_LINK := $(LIBS)

PGXS := $(shell $(PG_CONFIG) --pgxs)
include $(PGXS)
```

**Comment by csimsek** [comment]
Can you please remove your .so file. And try it from beginning (start with make clean) with root user. Also can you please send the output for 

`sudo pg_config`

Regards,

**Comment by loveencounterflow** [comment]
it worked! I just did `sudo make clean install`. I guess it must have been that step where I remove the `fio.so` which I had omitted prior to this. Thanks a lot for the help! 

BTW my most important use case is really reading text files line by line with line numbers to keep the ordering, do you plan on adding such functionality to pgsql-fio by any chance?

**Comment by csimsek** [comment]
Thank you.

And also thank you for your suggestion. It will be great. I'm adding to my TODO list.

Regards,
